export const mockedMoviesList = {
  ok: true,
  description: [
    {
      '#TITLE': 'Game of Thrones',
      '#YEAR': 2011,
      '#IMDB_ID': 'tt0944947',
      '#RANK': 33,
      '#ACTORS': 'Emilia Clarke, Peter Dinklage',
      '#AKA': 'Game of Thrones (2011)',
      '#IMDB_URL': 'https://imdb.com/title/tt0944947',
      '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt0944947&rhash=77ed0696a538f4',
      '#IMG_POSTER':
        'https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg',
      photo_width: 1000,
      photo_height: 1500,
    },
    {
      '#TITLE': `Grey's Anatomy`,
      '#YEAR': 2005,
      '#IMDB_ID': 'tt0413573',
      '#RANK': 38,
      '#ACTORS': 'Chandra Wilson, James Pickens Jr.',
      '#AKA': `Grey's Anatomy (2005)`,
      '#IMDB_URL': 'https://imdb.com/title/tt0413573',
      '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt0413573&rhash=77ed0696a538f4',
      '#IMG_POSTER':
        'https://m.media-amazon.com/images/M/MV5BODA2Mjk0N2MtNGY0Mi00ZWFjLTkxODEtZDFjNDg4ZDliMGVmXkEyXkFqcGdeQXVyMzAzNTY3MDM@._V1_.jpg',
      photo_width: 2700,
      photo_height: 4000,
    },
    {
      '#TITLE': 'The Gentlemen',
      '#YEAR': 2024,
      '#IMDB_ID': 'tt13210838',
      '#RANK': 1,
      '#ACTORS': 'Theo James, Kaya Scodelario',
      '#AKA': 'The Gentlemen (2024) ',
      '#IMDB_URL': 'https://imdb.com/title/tt13210838',
      '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt13210838&rhash=77ed0696a538f4',
      '#IMG_POSTER':
        'https://m.media-amazon.com/images/M/MV5BOGJjODQxYWUtYjlkOC00NzJiLTgyZjUtY2Q3Y2FhZGVlODEwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
      photo_width: 1500,
      photo_height: 2222,
    },
    {
      '#TITLE': 'Godzilla Minus One',
      '#YEAR': 2023,
      '#IMDB_ID': 'tt23289160',
      '#RANK': 49,
      '#ACTORS': 'Minami Hamabe, Sakura Andô',
      '#AKA': 'Godzilla Minus One (2023) ',
      '#IMDB_URL': 'https://imdb.com/title/tt23289160',
      '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt23289160&rhash=77ed0696a538f4',
      '#IMG_POSTER':
        'https://m.media-amazon.com/images/M/MV5BOTI5MjNjMTMtN2NiNC00YjBlLTgzMWQtMGRhZDZkYmY1NGU2XkEyXkFqcGdeQXVyNTgyNTA4MjM@._V1_.jpg',
      photo_width: 1168,
      photo_height: 1731,
    },
    {
      '#TITLE': 'Ghostbusters: Frozen Empire',
      '#YEAR': 2024,
      '#IMDB_ID': 'tt21235248',
      '#RANK': 73,
      '#ACTORS': 'Paul Rudd, Carrie Coon',
      '#AKA': 'Ghostbusters: Frozen Empire (2024) ',
      '#IMDB_URL': 'https://imdb.com/title/tt21235248',
      '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt21235248&rhash=77ed0696a538f4',
      '#IMG_POSTER':
        'https://m.media-amazon.com/images/M/MV5BNGE5MWJmZWYtN2ZlMi00ZjY1LTlhYTUtMzQ2Y2IxZWQyYTA2XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg',
      photo_width: 2024,
      photo_height: 3000,
    },
    {
      '#TITLE': 'Godzilla x Kong: The New Empire',
      '#YEAR': 2024,
      '#IMDB_ID': 'tt14539740',
      '#RANK': 76,
      '#ACTORS': 'Rebecca Hall, Brian Tyree Henry',
      '#AKA': 'Godzilla x Kong: The New Empire (2024) ',
      '#IMDB_URL': 'https://imdb.com/title/tt14539740',
      '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt14539740&rhash=77ed0696a538f4',
      '#IMG_POSTER':
        'https://m.media-amazon.com/images/M/MV5BN2VjZmI4NTctMmVjMy00NTc0LWE1YzAtMTE0MTg1ZDY2NmQyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg',
      photo_width: 2764,
      photo_height: 4096,
    },
    {
      '#TITLE': 'Ghosts',
      '#YEAR': 2021,
      '#IMDB_ID': 'tt11379026',
      '#RANK': 140,
      '#ACTORS': 'Rose McIver, Utkarsh Ambudkar',
      '#AKA': 'Ghosts (2021) ',
      '#IMDB_URL': 'https://imdb.com/title/tt11379026',
      '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt11379026&rhash=77ed0696a538f4',
      '#IMG_POSTER':
        'https://m.media-amazon.com/images/M/MV5BMWFjY2Y1ZTQtODAzMC00NmE4LThlM2EtNjBmN2M1YzI5NTZhXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg',
      photo_width: 2072,
      photo_height: 3000,
    },
    {
      '#TITLE': 'Girls5eva',
      '#YEAR': 2021,
      '#IMDB_ID': 'tt11650492',
      '#RANK': 204,
      '#ACTORS': 'Sara Bareilles, Busy Philipps',
      '#AKA': 'Girls5eva (2021)',
      '#IMDB_URL': 'https://imdb.com/title/tt11650492',
      '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt11650492&rhash=77ed0696a538f4',
      '#IMG_POSTER':
        'https://m.media-amazon.com/images/M/MV5BOGU0NjVhM2EtMzU3Zi00NGI5LWE2YWQtMWVmNjAyYmVmYWNkXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg',
      photo_width: 608,
      photo_height: 818,
    },
  ],
  error_code: 200,
};

export const mockedMovieDetails = {
  short: {
    '@context': 'https://schema.org',
    '@type': 'TVSeries',
    url: 'https://www.imdb.com/title/tt31027788/',
    name: 'Mahsun J',
    image:
      'https://m.media-amazon.com/images/M/MV5BZWU1OTZhOTctZjhmMC00NTVhLWE1NzYtNDFlNTYxMjAyYmE3XkEyXkFqcGdeQXVyNDg4MjkzNDk@._V1_.jpg',
    description: 'The interesting story of Mahsun who tried to become a gigolo while working as a courier.',
    review: {
      '@type': 'Review',
      itemReviewed: {
        '@type': 'TVSeries',
        url: 'https://www.imdb.com/title/tt31027788/',
      },
      author: {
        '@type': 'Person',
        name: 'aliyagmur-60778',
      },
      dateCreated: '2024-02-09',
      inLanguage: 'English',
      name: 'Love This',
      reviewBody:
        'Mahsun Karaca started with short videos and proved himself in the field of films and TV series. The scenario does not have an exaggerated story, what makes this series special is that a YouTube phenomenon can make such a good comedy. While the comedy projects of old stars such as Cem Yilmaz, Ata Demirer and Ahmet Kural are fading, Mahsun Karaca now clearly shows who owns the throne. I also liked Yosi Mizrahi&apos;s acting very much, I can say that the character he portrays is almost himself. Mahsun Karaca, who makes very high quality comedies with very small budgets, gave the necessary answer for the industry.',
      reviewRating: {
        '@type': 'Rating',
        worstRating: 2,
        bestRating: 8,
        ratingValue: 7,
      },
    },
    aggregateRating: {
      '@type': 'AggregateRating',
      ratingCount: 6876,
      bestRating: 10,
      worstRating: 1,
      ratingValue: 8.5,
    },
    genre: ['Comedy'],
    datePublished: '2024-01-26',
    actor: [
      {
        '@type': 'Person',
        url: 'https://www.imdb.com/name/nm10018889/',
        name: 'Mahsun Karaca',
      },
      {
        '@type': 'Person',
        url: 'https://www.imdb.com/name/nm10114798/',
        name: 'Eda Akalin',
      },
      {
        '@type': 'Person',
        url: 'https://www.imdb.com/name/nm11962208/',
        name: 'Tugçe Yolcu',
      },
    ],
    creator: [
      {
        '@type': 'Organization',
        url: 'https://www.imdb.com/company/co0855831/',
      },
    ],
  },
  imdbId: 'tt31027788',
  fake: {
    '#TITLE': 'Mahsun J',
    '#YEAR': 2024,
    '#IMDB_ID': 'tt31027788',
    '#RANK': 4520,
    '#ACTORS': 'Mahsun Karaca, Eda Akalin',
    '#AKA': 'Mahsun J (2024) ',
    '#IMDB_URL': 'https://imdb.com/title/tt31027788',
    '#IMDB_IV': 'https://t.me/iv?url=https%3A%2F%2Fimdb.com%2Ftitle%2Ftt31027788&rhash=77ed0696a538f4',
    '#IMG_POSTER':
      'https://m.media-amazon.com/images/M/MV5BZWU1OTZhOTctZjhmMC00NTVhLWE1NzYtNDFlNTYxMjAyYmE3XkEyXkFqcGdeQXVyNDg4MjkzNDk@._V1_.jpg',
    photo_width: 2160,
    photo_height: 2700,
  },
};
